### ISSUE TITLE
Build error due to SupportedFileType in NativeFileSOBuild.cs -> PostProcessIOS

### ISSUE THREAD

**Issue by aidanwolf** [keiwando/nativefileso#2]
Thank you for making such an awesome package, it works perfectly on device but I do have to manually set up DocumentType, Import/Export UTIs because of this build error. Here's the console output:

![Screen Shot 2020-07-16 at 5 17 17 PM](https://user-images.githubusercontent.com/9259668/87726132-76297a00-c78c-11ea-9035-743d18856436.png)

**Comment by keiwando** [comment]
Does it say on which line the `ArgumentNullException` is thrown?

**Comment by aidanwolf** [comment]
Hi Keiwan! Figured it out, these lines in _NativeFileSOBuild.cs_ are deprecated in the version of Unity I have (2019.3.15f1), switched it to the new line and it works.

```
var targetName = PBXProject.GetUnityTargetName();
var targetGUID = project.TargetGuidByName(targetName);
```

`var targetGUID = project.GetUnityFrameworkTargetGuid();`

I wrongly assumed it was due to SupportedFileTypes because of this line
```
if (SupportedFilePreferences.supportedFileTypes.Length == 0) {
return;
}
```

Thanks! All the best to you.

**Comment by keiwando** [comment]
Thanks for pointing this out and also finding the solution! I fixed it and uploaded a new release:
https://github.com/keiwando/nativefileso/releases/tag/v1.0.2

Now it should work on Unity versions below and above 2019.3
